 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/citizens", type: :request do
  # Citizen. As you add validations to Citizen, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Citizen.create! valid_attributes
      get citizens_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      citizen = Citizen.create! valid_attributes
      get citizen_url(citizen)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_citizen_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      citizen = Citizen.create! valid_attributes
      get edit_citizen_url(citizen)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Citizen" do
        expect {
          post citizens_url, params: { citizen: valid_attributes }
        }.to change(Citizen, :count).by(1)
      end

      it "redirects to the created citizen" do
        post citizens_url, params: { citizen: valid_attributes }
        expect(response).to redirect_to(citizen_url(Citizen.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Citizen" do
        expect {
          post citizens_url, params: { citizen: invalid_attributes }
        }.to change(Citizen, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post citizens_url, params: { citizen: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested citizen" do
        citizen = Citizen.create! valid_attributes
        patch citizen_url(citizen), params: { citizen: new_attributes }
        citizen.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the citizen" do
        citizen = Citizen.create! valid_attributes
        patch citizen_url(citizen), params: { citizen: new_attributes }
        citizen.reload
        expect(response).to redirect_to(citizen_url(citizen))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        citizen = Citizen.create! valid_attributes
        patch citizen_url(citizen), params: { citizen: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested citizen" do
      citizen = Citizen.create! valid_attributes
      expect {
        delete citizen_url(citizen)
      }.to change(Citizen, :count).by(-1)
    end

    it "redirects to the citizens list" do
      citizen = Citizen.create! valid_attributes
      delete citizen_url(citizen)
      expect(response).to redirect_to(citizens_url)
    end
  end
end
